# Generated by Django 4.1 on 2022-09-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alertTitle', models.CharField(max_length=100)),
                ('alertFile', models.FileField(upload_to='alert')),
                ('alertDate', models.DateField()),
                ('alertIntensity', models.CharField(choices=[('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('light', 'light')], max_length=50)),
            ],
        ),
    ]
