# Generated by Django 4.1 on 2022-09-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticeboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticeTitle', models.CharField(max_length=200)),
                ('noticeFile', models.FileField(upload_to='noticeboard')),
                ('noticeUrl', models.URLField(null=True)),
                ('noticeDate', models.DateField()),
            ],
        ),
    ]
