# Generated by Django 4.1 on 2022-09-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0003_upcominglect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcominglect',
            name='lectureDate',
            field=models.DateTimeField(),
        ),
    ]
