# Generated by Django 4.1 on 2022-09-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0004_alter_upcominglect_lecturedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altText', models.CharField(max_length=50, null=True)),
                ('logoLink', models.URLField()),
                ('logoImage', models.FileField(upload_to='flogo')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
