# Generated by Django 4.1 on 2022-09-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0005_featuredlogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlimpseSW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ImageField(height_field=True, upload_to='studentsglimplse', width_field=True)),
                ('altText', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
