# Generated by Django 4.1 on 2022-09-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0007_rename_title_glimpsesw_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glimpsesw',
            name='image',
            field=models.ImageField(upload_to='studentsglimplse'),
        ),
    ]
