# Generated by Django 4.1 on 2022-09-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0010_techanicalofficer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techanicalofficer',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
