# Generated by Django 4.1 on 2022-09-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0011_alter_techanicalofficer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemadmin',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
