# Generated by Django 4.1 on 2022-09-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0012_alter_systemadmin_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor')], max_length=50)),
                ('qualifications', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14)),
                ('profile_Pic', models.ImageField(max_length=254, upload_to='profiles')),
                ('date', models.DateField(auto_now=True)),
                ('cv', models.FileField(upload_to='cv')),
                ('Publications', models.URLField()),
            ],
        ),
    ]
