# Generated by Django 4.1 on 2022-09-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0014_chairperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('designation', models.CharField(choices=[('Director', 'Director'), ('Director in Charge ', 'Director in Charge ')], max_length=50)),
                ('date', models.DateField()),
                ('profile_Pic', models.ImageField(max_length=254, upload_to='profiles')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14)),
                ('cv', models.FileField(default=None, upload_to='cv')),
                ('Publications', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='chairperson',
            name='cv',
            field=models.FileField(default='None', upload_to='cv'),
        ),
        migrations.AddField(
            model_name='chairperson',
            name='email',
            field=models.EmailField(default='cv', max_length=254),
        ),
        migrations.AddField(
            model_name='chairperson',
            name='phone',
            field=models.CharField(default=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='cv',
            field=models.FileField(default='cv', upload_to='cv'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='phone',
            field=models.CharField(default=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='techanicalofficer',
            name='phone',
            field=models.CharField(default=True, max_length=14),
        ),
    ]
