# Generated by Django 4.1 on 2022-09-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0015_director_chairperson_cv_chairperson_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(choices=[('Chairperson', 'Chairperson'), ('Director SPAV - Ex-Officio - Member', 'Director SPAV - Ex-Officio - Member'), ('Pr. Secretary - GoAP - Member', 'Pr. Secretary - GoAP - Member'), ('Rep. from ITPI - Member', 'Rep. from ITPI - Member'), ('Rep. from AICTE- Member', 'Rep. from AICTE- Member'), ('Rep. from UGC- Member', 'Rep. from UGC- Member'), ('Rep. from CoA- Member', 'Rep. from CoA- Member'), ('JS &FA, MoE - Member', 'JS &FA, MoE - Member'), ('Nominee of MoE - Member', 'Nominee of MoE - Member'), ('Nominee of MoUD- Member', 'Nominee of MoUD- Member'), ('Senate Nominee - 1 (DoA) - Member', 'Senate Nominee - 1 (DoA) - Member'), ('Senate Nominee - 2 (DoP) - Member', 'Senate Nominee - 2 (DoP) - Member'), ('Registrar SPAV - Ex-Officio - Secretary', 'Registrar SPAV - Ex-Officio - Secretary')], max_length=50)),
                ('profile_Pic', models.ImageField(max_length=254, upload_to='profiles')),
                ('date', models.DateField()),
            ],
        ),
    ]
