# Generated by Django 4.1 on 2022-09-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0017_remove_bog_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altText', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='slider')),
                ('link', models.URLField(null=True)),
            ],
        ),
    ]
