# Generated by Django 4.1 on 2022-09-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0018_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(choices=[('Chairperson Finance Commitee', 'Chairperson Finance Commitee'), ('Secoratry Finance Commitee', 'Secoratry Finance Commitee')], max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
