# Generated by Django 4.1 on 2022-09-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0019_fc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bwc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(choices=[('Chairperson BWC Commitee', 'Chairperson BWC Commitee'), ('Secoratry BWC Commitee', 'Secoratry BWC Commitee')], max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
