# Generated by Django 4.1 on 2022-09-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0020_bwc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Senate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(choices=[('Chairman Senate', 'Chairman Senate'), ('Dy Senate', 'Dy Senate')], max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
