# Generated by Django 4.1 on 2022-09-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0021_senate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(choices=[('Dean Academics', 'Dean Academics'), ('Dean Planning and Development', 'Dean Planning and Development'), ('Dean Students Affair', 'Dean Students Affair'), ('Dean Faculty Welfare', 'Dean Faculty Welfare'), ('Dean Research', 'Dean Research')], max_length=50)),
                ('profile_Pic', models.ImageField(max_length=254, upload_to='profiles')),
                ('email', models.EmailField(default='cv', max_length=254)),
                ('phone', models.CharField(default=True, max_length=14)),
                ('date', models.DateField()),
            ],
        ),
    ]
