# Generated by Django 4.1 on 2022-09-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0022_deans'),
    ]

    operations = [
        migrations.AddField(
            model_name='deans',
            name='duties',
            field=models.TextField(default='Duties'),
        ),
    ]
