# Generated by Django 4.1 on 2022-09-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0025_remove_deans_duties'),
    ]

    operations = [
        migrations.AddField(
            model_name='deans',
            name='duties',
            field=models.TextField(default='Duties and Responsibilities of Deans'),
        ),
    ]
