# Generated by Django 4.1 on 2022-09-09 06:41

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0026_deans_duties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deans',
            name='duties',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
