# Generated by Django 4.1 on 2022-09-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0028_alter_deans_duties'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(choices=[('Registrar', 'Registrar'), ('Assistant Registrar', 'Assistant Registrar'), ('DY. Librarian', 'DY. Librarian'), ('System Administrator', 'System Administrator'), ('Assistant Librarian', 'Assistant Librarian'), ('Technical Officer', 'Technical Officer'), ('Assistant Engineer Cum Project Officer', 'Assistant Engineer Cum Project Officer'), ('Accountant, Accounts Section', 'Accountant, Accounts Section'), ('Multi-Skill Assistant, Director`s Office', 'Multi-Skill Assistant, Director`s Office'), ('Multi Skill Assistant', 'Multi Skill Assistant'), ('Junior Engineer Civil', 'Junior Engineer Civil'), ('Junior Engineer Electrical', 'Junior Engineer Electrical'), ('Accountant', 'Accountant'), ('Library Assistant', 'Library Assistant'), ('Lab Attendant', 'Lab Attendant')], max_length=50)),
                ('profile_Pic', models.ImageField(max_length=254, upload_to='profiles')),
                ('email', models.EmailField(default='cv', max_length=254)),
                ('phone', models.CharField(default=True, max_length=14)),
                ('date', models.DateField()),
            ],
        ),
    ]
