# Generated by Django 4.1 on 2022-09-09 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0029_administration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('designation', models.CharField(choices=[('Professor', 'Professor'), ('Assistant Professorr', 'Assistant Professorr')], max_length=50)),
                ('department', models.CharField(choices=[('Architecture', 'Architecture'), ('Planning', 'Planning')], max_length=50)),
                ('profile_Pic', models.ImageField(max_length=254, upload_to='profiles')),
                ('email', models.EmailField(default='cv', max_length=254)),
                ('phone', models.CharField(default=True, max_length=14)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Commitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spav.faculty')),
            ],
            options={
                'ordering': ['headline'],
            },
        ),
    ]
